---

repos:
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-symlinks
    - id: detect-private-key
- repo: "https://github.com/aquasecurity/tfsec"
  rev: v1.28.1
  hooks:
    - id: tfsec-system
# - repo: "https://github.com/terraform-docs/terraform-docs"
#   rev: v0.16.0
#   hooks:
#     - id: terraform-docs-go
#       args: ["markdown", "table", "--output-file", "README.md", "./"]

...
